### ISSUE TITLE
Build failed at Ubuntu 18.04

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/rocFFT#131]
### What actually happens
-  /opt/rocm/hip/include/hip/hcc_detail/hip_runtime.h:76:10: fatal error: 'grid_launch.h' file not found

### How to reproduce
-  build on Ubuntu 18.04

### Environment

| HCC | HCC 1.2.18313-39ff360d-be6eeeeffb-1e422702eba|
 

 /ROCm/rocFFT/release$ make
Scanning dependencies of target rocfft-kernel-generator
[  4%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.main.cpp.o
[  8%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.file.cpp.o
[ 12%] Linking CXX executable rocfft-kernel-generator
[ 12%] Built target rocfft-kernel-generator
[ 16%] Generator producing device kernels for rocfft-device
Scanning dependencies of target rocfft-device
[ 20%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/transpose.cpp.o
In file included from /home/runtron/ROCm/rocFFT/library/src/device/transpose.cpp:6:
In file included from /home/runtron/ROCm/rocFFT/library/src/device/../include/kernel_launch.h:12:
In file included from /home/runtron/ROCm/rocFFT/library/src/device/../include/rocfft_hip.h:9:
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:56:
/opt/rocm/hip/include/hip/hcc_detail/hip_runtime.h:76:10: fatal error: 'grid_launch.h' file not found
#include <grid_launch.h>
         ^~~~~~~~~~~~~~~
1 error generated.
library/src/device/CMakeFiles/rocfft-device.dir/build.make:504: recipe for target 'library/src/device/CMakeFiles/rocfft-device.dir/transpose.cpp.o' failed
make[2]: *** [library/src/device/CMakeFiles/rocfft-device.dir/transpose.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'library/src/device/CMakeFiles/rocfft-device.dir/all' failed
make[1]: *** [library/src/device/CMakeFiles/rocfft-device.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psteinb** [comment]
looks like the include paths are wrong as `grid_launch.h` is installed under `/opt/rocm/hcc/include/grid_launch.h` at least in my rocm installation. As I am not the developer of this package, I can only suggest to provide more details, e.g. which commit of rocfft did you use.

**Comment by bragadeesh** [comment]
Is this master branch? Did you try develop branch?
It had a fix for this issue I believe which builds with hip::device as opposed to hip::hip_hcc

**Comment by wormwang** [comment]
rerun make , same issue at today.
I confused why cmake can not find the grid_launch.h at Ubuntu 18.04, at same time it can find the same grid_launch.h at ubuntu 16.04

**Comment by bragadeesh** [comment]
can you try the ./install.sh script and see if you can build

**Comment by wormwang** [comment]
Could not find compiler set in environment variable CXX:

  hcc.

Call Stack (most recent call first):
  CMakeLists.txt:23 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by bragadeesh** [comment]
so ubuntu 18.04 + rocfft master branch + rocm 1.8.192 + 'install.sh -cd' command in rocfft 
this is the combo you are trying? what gpu do you have? do you have any cuda sw installed?

**Comment by malcolmroberts** [comment]
I've successfully compiled rocFFT on Ubuntu 18.  Is this still an issue, or can we close it?
